---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi
provisioner: file.csi.azure.com
parameters:
  resourceGroup: EXISTING_RESOURCE_GROUP_NAME
  storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
  shareName: SHARE_NAME
  diskName: EXISTING_DISK_NAME
  vhdFsType: ext4  # available values: cifs, ext4, ext3, ext2, xfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
